apiVersion: batch/v1
kind: Job
metadata:
  name: nvidia-probe
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      nodeSelector:
        cloud.google.com/gke-nodepool: gpu-node-pool
      tolerations:
        - key: nvidia.com/gpu
          operator: Equal
          value: present
          effect: NoSchedule
      containers:
        - name: nvidia-probe
          image: ghcr.io/shadi/nvidia-probe:latest
          securityContext:
            privileged: true
          volumeMounts:
            - name: host
              mountPath: /host
              readOnly: true
      volumes:
        - name: host
          hostPath:
            path: /
